# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 995919df9f361c5954902878052ab8c9f238ad37b4ee5807249c254ba7e4ea0f45501c6f73200ddfa521b585de781047ba087285b46cded0b003e676ee53b677

test:
  secret_key_base: 448f3417768c583e104d2142068057b6d8faf103e8dcfa3f5f98ad5858bc06d9f37fa9c0fe0fec961690f7ce554d5eee11b34309ab69f6f8242bb1a361739507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
